import { Genre, Movie } from '../types';

export const GENRES_LIST: Genre[] = [
  { id: 28, name: 'Action', icon: '🎬', gradient: 'from-amber-500/20 to-red-600/20 border-red-500/30' },
  { id: 12, name: 'Adventure', icon: '🧭', gradient: 'from-emerald-500/20 to-teal-600/20 border-emerald-500/30' },
  { id: 16, name: 'Animation', icon: '🎨', gradient: 'from-pink-500/20 to-purple-600/20 border-pink-500/30' },
  { id: 35, name: 'Comedy', icon: '😂', gradient: 'from-yellow-500/20 to-amber-600/20 border-yellow-500/30' },
  { id: 80, name: 'Crime', icon: '🕵️', gradient: 'from-zinc-500/20 to-neutral-700/20 border-neutral-500/30' },
  { id: 99, name: 'Documentary', icon: '📽️', gradient: 'from-cyan-500/20 to-blue-600/20 border-cyan-500/30' },
  { id: 18, name: 'Drama', icon: '🎭', gradient: 'from-indigo-500/20 to-violet-600/20 border-indigo-500/30' },
  { id: 14, name: 'Fantasy', icon: '🐉', gradient: 'from-purple-500/20 to-fuchsia-600/20 border-purple-500/30' },
  { id: 27, name: 'Horror', icon: '👻', gradient: 'from-rose-900/30 to-red-950/30 border-rose-600/30' },
  { id: 9648, name: 'Mystery', icon: '🔍', gradient: 'from-slate-600/20 to-indigo-900/20 border-slate-500/30' },
  { id: 10749, name: 'Romance', icon: '❤️', gradient: 'from-rose-500/20 to-pink-600/20 border-rose-500/30' },
  { id: 878, name: 'Science Fiction', icon: '🚀', gradient: 'from-cyan-600/20 to-blue-800/20 border-cyan-500/30' },
  { id: 53, name: 'Thriller', icon: '⚡', gradient: 'from-orange-600/20 to-red-800/20 border-orange-500/30' },
];

export const MOCK_MOVIES: Movie[] = [
  {
    id: 693134,
    title: 'Dune: Part Two',
    tagline: 'Long live the fighters.',
    overview: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he endeavors to prevent a terrible future only he can foresee.',
    poster_path: 'https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520b42.jpg',
    release_date: '2024-03-01',
    vote_average: 8.2,
    vote_count: 5320,
    popularity: 98.4,
    runtime: 166,
    genres: [
      { id: 878, name: 'Science Fiction' },
      { id: 12, name: 'Adventure' },
      { id: 18, name: 'Drama' },
    ],
    genre_ids: [878, 12, 18],
    director: 'Denis Villeneuve',
    cast: [
      { id: 1190668, name: 'Timothée Chalamet', character: 'Paul Atreides', profile_path: 'https://image.tmdb.org/t/p/w300/BE2sdjpgsa2rNTFa66f7upkaOP.jpg' },
      { id: 505710, name: 'Zendaya', character: 'Chani', profile_path: 'https://image.tmdb.org/t/p/w300/so3G5b65SYGkO1Hgk2T6Y6v9y88.jpg' },
      { id: 934, name: 'Rebecca Ferguson', character: 'Lady Jessica', profile_path: 'https://image.tmdb.org/t/p/w300/4zLOqQ64g0J0u9qFqHhIeS6PzT3.jpg' },
      { id: 27488, name: 'Javier Bardem', character: 'Stilgar', profile_path: 'https://image.tmdb.org/t/p/w300/gT8Vd6U901mCj9XQW2b4xK4m20p.jpg' },
      { id: 1373737, name: 'Florence Pugh', character: 'Princess Irulan', profile_path: 'https://image.tmdb.org/t/p/w300/fhAPZlH5jN2G2nJ3N2hQY31K1a4.jpg' },
      { id: 1391986, name: 'Austin Butler', character: 'Feyd-Rautha Harkonnen', profile_path: 'https://image.tmdb.org/t/p/w300/2F132Yv1WlO18Zg4d0p0R3e18m3.jpg' },
    ],
    budget: 190000000,
    revenue: 711844358,
    status: 'Released',
    trailer_key: 'Way9Dexny3w',
    spoken_languages: ['English', 'Fremen', 'Chakobsa'],
    production_companies: [
      { id: 923, name: 'Legendary Pictures' },
      { id: 174, name: 'Warner Bros. Pictures' },
    ],
  },
  {
    id: 872585,
    title: 'Oppenheimer',
    tagline: 'The world forever changes.',
    overview: 'The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II, examining the moral, geopolitical, and personal turmoil surrounding the dawn of the nuclear era.',
    poster_path: 'https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    release_date: '2023-07-21',
    vote_average: 8.1,
    vote_count: 8900,
    popularity: 92.1,
    runtime: 180,
    genres: [
      { id: 18, name: 'Drama' },
      { id: 36, name: 'History' },
    ],
    genre_ids: [18, 99],
    director: 'Christopher Nolan',
    cast: [
      { id: 2037, name: 'Cillian Murphy', character: 'J. Robert Oppenheimer', profile_path: 'https://image.tmdb.org/t/p/w300/dm6VwW04l2LqK0j2b6lq4G3h3r7.jpg' },
      { id: 5081, name: 'Emily Blunt', character: 'Kitty Oppenheimer', profile_path: 'https://image.tmdb.org/t/p/w300/hG01U0Kz7B0p7w7M0U8k12k8s2F.jpg' },
      { id: 3223, name: 'Robert Downey Jr.', character: 'Lewis Strauss', profile_path: 'https://image.tmdb.org/t/p/w300/5qHNjhtjMD4YWH3ez6CCm2tiq0s.jpg' },
      { id: 1892, name: 'Matt Damon', character: 'Leslie Groves', profile_path: 'https://image.tmdb.org/t/p/w300/elSlNg0WjdTbg8J9i4g1a1a5p7z.jpg' },
    ],
    budget: 100000000,
    revenue: 957800000,
    status: 'Released',
    trailer_key: 'uYPbbksJxIg',
    spoken_languages: ['English', 'German', 'Dutch'],
    production_companies: [
      { id: 33, name: 'Universal Pictures' },
      { id: 9996, name: 'Syncopy' },
    ],
  },
  {
    id: 569094,
    title: 'Spider-Man: Across the Spider-Verse',
    tagline: 'It\'s how you wear the mask that matters.',
    overview: 'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider-Society, a team of Spider-People charged with protecting the Multiverse’s very existence.',
    poster_path: 'https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    release_date: '2023-06-02',
    vote_average: 8.4,
    vote_count: 6700,
    popularity: 88.7,
    runtime: 140,
    genres: [
      { id: 16, name: 'Animation' },
      { id: 28, name: 'Action' },
      { id: 12, name: 'Adventure' },
      { id: 878, name: 'Science Fiction' },
    ],
    genre_ids: [16, 28, 12, 878],
    director: 'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson',
    cast: [
      { id: 587506, name: 'Shameik Moore', character: 'Miles Morales (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/4g0H4Yn8u9H5J6a7b3c2d1e0f.jpg' },
      { id: 54693, name: 'Hailee Steinfeld', character: 'Gwen Stacy (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/2A8d0xG7m3X8a1l4j7b0z2x8c.jpg' },
      { id: 23659, name: 'Oscar Isaac', character: 'Miguel O\'Hara (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/cYg0kLp6m8P2b4n0s8a1m5k8g.jpg' },
      { id: 1475727, name: 'Daniel Kaluuya', character: 'Hobart \'Hobie\' Brown (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/4h8r9k0b4v6c7z8a9m0p1q2r3.jpg' },
    ],
    budget: 100000000,
    revenue: 690516673,
    status: 'Released',
    trailer_key: 'cqGjhVJWtEg',
    spoken_languages: ['English', 'Spanish', 'Hindi'],
    production_companies: [
      { id: 5, name: 'Columbia Pictures' },
      { id: 2251, name: 'Sony Pictures Animation' },
      { id: 7505, name: 'Marvel Entertainment' },
    ],
  },
  {
    id: 157336,
    title: 'Interstellar',
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    poster_path: 'https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/rAiYTsqOdikIpC0yWTMqu10nBqP.jpg',
    release_date: '2014-11-07',
    vote_average: 8.4,
    vote_count: 34500,
    popularity: 95.3,
    runtime: 169,
    genres: [
      { id: 12, name: 'Adventure' },
      { id: 18, name: 'Drama' },
      { id: 878, name: 'Science Fiction' },
    ],
    genre_ids: [12, 18, 878],
    director: 'Christopher Nolan',
    cast: [
      { id: 10297, name: 'Matthew McConaughey', character: 'Cooper', profile_path: 'https://image.tmdb.org/t/p/w300/ehoFq188K9G7v9m5l9s0n8b3v.jpg' },
      { id: 1813, name: 'Anne Hathaway', character: 'Brand', profile_path: 'https://image.tmdb.org/t/p/w300/9k8kL5q7p0s8n1m9k2b3v4c5d.jpg' },
      { id: 83002, name: 'Jessica Chastain', character: 'Murph', profile_path: 'https://image.tmdb.org/t/p/w300/4z9r0n8v1m2c3b4x5z6a7s8d9.jpg' },
      { id: 3895, name: 'Michael Caine', character: 'Professor Brand', profile_path: 'https://image.tmdb.org/t/p/w300/1s2d3f4g5h6j7k8l9z0x1c2v3.jpg' },
    ],
    budget: 165000000,
    revenue: 773800000,
    status: 'Released',
    trailer_key: 'zSWdZVtXT7E',
    spoken_languages: ['English'],
    production_companies: [
      { id: 923, name: 'Legendary Pictures' },
      { id: 9996, name: 'Syncopy' },
      { id: 4, name: 'Paramount' },
    ],
  },
  {
    id: 155,
    title: 'The Dark Knight',
    tagline: 'Welcome to a world without rules.',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
    poster_path: 'https://image.tmdb.org/t/p/w780/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    release_date: '2008-07-18',
    vote_average: 8.5,
    vote_count: 32000,
    popularity: 96.8,
    runtime: 152,
    genres: [
      { id: 18, name: 'Drama' },
      { id: 28, name: 'Action' },
      { id: 80, name: 'Crime' },
      { id: 53, name: 'Thriller' },
    ],
    genre_ids: [18, 28, 80, 53],
    director: 'Christopher Nolan',
    cast: [
      { id: 3894, name: 'Christian Bale', character: 'Bruce Wayne / Batman', profile_path: 'https://image.tmdb.org/t/p/w300/b7fTD938IP9wf929qdMuRI9g0.jpg' },
      { id: 1810, name: 'Heath Ledger', character: 'Joker', profile_path: 'https://image.tmdb.org/t/p/w300/pE02r9T1F1Y8y1s0n8b3v9.jpg' },
      { id: 3895, name: 'Michael Caine', character: 'Alfred Pennyworth', profile_path: 'https://image.tmdb.org/t/p/w300/1s2d3f4g5h6j7k8l9z0x1c2v3.jpg' },
      { id: 64, name: 'Gary Oldman', character: 'James Gordon', profile_path: 'https://image.tmdb.org/t/p/w300/8tVq3b4m2c5v6z7a8s9d0f1.jpg' },
    ],
    budget: 185000000,
    revenue: 1004558444,
    status: 'Released',
    trailer_key: 'EXeTwQWrcwY',
    spoken_languages: ['English', 'Mandarin'],
    production_companies: [
      { id: 174, name: 'Warner Bros. Pictures' },
      { id: 923, name: 'Legendary Pictures' },
      { id: 9996, name: 'Syncopy' },
    ],
  },
  {
    id: 299534,
    title: 'Avengers: Endgame',
    tagline: 'Part of the journey is the end.',
    overview: 'After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos\'s actions and restore balance to the universe, no matter what consequences may be in store.',
    poster_path: 'https://image.tmdb.org/t/p/w780/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
    release_date: '2019-04-26',
    vote_average: 8.3,
    vote_count: 24800,
    popularity: 91.2,
    runtime: 181,
    genres: [
      { id: 12, name: 'Adventure' },
      { id: 878, name: 'Science Fiction' },
      { id: 28, name: 'Action' },
    ],
    genre_ids: [12, 878, 28],
    director: 'Anthony Russo, Joe Russo',
    cast: [
      { id: 3223, name: 'Robert Downey Jr.', character: 'Tony Stark / Iron Man', profile_path: 'https://image.tmdb.org/t/p/w300/5qHNjhtjMD4YWH3ez6CCm2tiq0s.jpg' },
      { id: 16828, name: 'Chris Evans', character: 'Steve Rogers / Captain America', profile_path: 'https://image.tmdb.org/t/p/w300/3bOGNsHlrswhyW79uvIHH1V43JI.jpg' },
      { id: 1245, name: 'Scarlett Johansson', character: 'Natasha Romanoff / Black Widow', profile_path: 'https://image.tmdb.org/t/p/w300/6NsMbJXRlDZuDzatN2akFdGuTvx.jpg' },
      { id: 74568, name: 'Chris Hemsworth', character: 'Thor Odinson', profile_path: 'https://image.tmdb.org/t/p/w300/jpurJ9jAcLCYjgHHfYF32m3eR8m.jpg' },
      { id: 103, name: 'Mark Ruffalo', character: 'Bruce Banner / Hulk', profile_path: 'https://image.tmdb.org/t/p/w300/z3xFa9z6s28G09k8n0b3v4c5d.jpg' },
    ],
    budget: 356000000,
    revenue: 2799439100,
    status: 'Released',
    trailer_key: 'TcMBFSGVi1c',
    spoken_languages: ['English', 'Japanese', 'Xhosa'],
    production_companies: [
      { id: 420, name: 'Marvel Studios' },
    ],
  },
  {
    id: 27205,
    title: 'Inception',
    tagline: 'Your mind is the scene of the crime.',
    overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
    poster_path: 'https://image.tmdb.org/t/p/w780/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    release_date: '2010-07-16',
    vote_average: 8.4,
    vote_count: 36000,
    popularity: 90.0,
    runtime: 148,
    genres: [
      { id: 28, name: 'Action' },
      { id: 878, name: 'Science Fiction' },
      { id: 12, name: 'Adventure' },
    ],
    genre_ids: [28, 878, 12],
    director: 'Christopher Nolan',
    cast: [
      { id: 6193, name: 'Leonardo DiCaprio', character: 'Dom Cobb', profile_path: 'https://image.tmdb.org/t/p/w300/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg' },
      { id: 24045, name: 'Joseph Gordon-Levitt', character: 'Arthur', profile_path: 'https://image.tmdb.org/t/p/w300/4GXNzjG4R1N6z0s9k8b3v4c.jpg' },
      { id: 27578, name: 'Elliot Page', character: 'Ariadne', profile_path: 'https://image.tmdb.org/t/p/w300/5m8z0v9k8b3v4c5d6e7f8g9h0.jpg' },
      { id: 2524, name: 'Tom Hardy', character: 'Eames', profile_path: 'https://image.tmdb.org/t/p/w300/d8joFvjghvPhXo14pAasfD7fA.jpg' },
    ],
    budget: 160000000,
    revenue: 836836967,
    status: 'Released',
    trailer_key: 'YoHD9XEInc0',
    spoken_languages: ['English', 'Japanese', 'French'],
    production_companies: [
      { id: 923, name: 'Legendary Pictures' },
      { id: 9996, name: 'Syncopy' },
      { id: 174, name: 'Warner Bros. Pictures' },
    ],
  },
  {
    id: 545611,
    title: 'Everything Everywhere All at Once',
    tagline: 'The universe is so much bigger than you realize.',
    overview: 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what is important to her by connecting with the lives she could have led across alternate dimensions.',
    poster_path: 'https://image.tmdb.org/t/p/w780/w3LxiVYPqNkQpRbaT9PzbNDzyNk.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/ss0Os3uWk1i178oG2Z5mY65ZtWb.jpg',
    release_date: '2022-03-25',
    vote_average: 8.0,
    vote_count: 6100,
    popularity: 76.5,
    runtime: 139,
    genres: [
      { id: 28, name: 'Action' },
      { id: 12, name: 'Adventure' },
      { id: 878, name: 'Science Fiction' },
      { id: 35, name: 'Comedy' },
    ],
    genre_ids: [28, 12, 878, 35],
    director: 'Daniel Kwan, Daniel Scheinert',
    cast: [
      { id: 1620, name: 'Michelle Yeoh', character: 'Evelyn Wang', profile_path: 'https://image.tmdb.org/t/p/w300/4z9r0n8v1m2c3b4x5z6a7s8d9.jpg' },
      { id: 62234, name: 'Ke Huy Quan', character: 'Waymond Wang', profile_path: 'https://image.tmdb.org/t/p/w300/5m8z0v9k8b3v4c5d6e7f8g9h0.jpg' },
      { id: 15303, name: 'Jamie Lee Curtis', character: 'Deirdre Beaubeirdre', profile_path: 'https://image.tmdb.org/t/p/w300/d8joFvjghvPhXo14pAasfD7fA.jpg' },
      { id: 2049994, name: 'Stephanie Hsu', character: 'Joy Wang / Jobu Tupaki', profile_path: 'https://image.tmdb.org/t/p/w300/cYg0kLp6m8P2b4n0s8a1m5k8g.jpg' },
    ],
    budget: 25000000,
    revenue: 141200000,
    status: 'Released',
    trailer_key: 'wxN1T1uxQ2g',
    spoken_languages: ['English', 'Mandarin', 'Cantonese'],
    production_companies: [
      { id: 41077, name: 'A24' },
      { id: 82819, name: 'AGBO' },
    ],
  },
  {
    id: 414906,
    title: 'The Batman',
    tagline: 'Unmask the truth.',
    overview: 'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler who targets Gotham\'s corrupt elite.',
    poster_path: 'https://image.tmdb.org/t/p/w780/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg',
    release_date: '2022-03-04',
    vote_average: 7.7,
    vote_count: 9800,
    popularity: 82.3,
    runtime: 176,
    genres: [
      { id: 80, name: 'Crime' },
      { id: 9648, name: 'Mystery' },
      { id: 53, name: 'Thriller' },
      { id: 28, name: 'Action' },
    ],
    genre_ids: [80, 9648, 53, 28],
    director: 'Matt Reeves',
    cast: [
      { id: 11288, name: 'Robert Pattinson', character: 'Bruce Wayne / The Batman', profile_path: 'https://image.tmdb.org/t/p/w300/4g0H4Yn8u9H5J6a7b3c2d1e0f.jpg' },
      { id: 37153, name: 'Zoë Kravitz', character: 'Selina Kyle / Catwoman', profile_path: 'https://image.tmdb.org/t/p/w300/2A8d0xG7m3X8a1l4j7b0z2x8c.jpg' },
      { id: 5293, name: 'Paul Dano', character: 'Edward Nashton / The Riddler', profile_path: 'https://image.tmdb.org/t/p/w300/cYg0kLp6m8P2b4n0s8a1m5k8g.jpg' },
      { id: 7248, name: 'Colin Farrell', character: 'Oswald Cobblepot / The Penguin', profile_path: 'https://image.tmdb.org/t/p/w300/4h8r9k0b4v6c7z8a9m0p1q2r3.jpg' },
    ],
    budget: 185000000,
    revenue: 772245583,
    status: 'Released',
    trailer_key: 'mqqft2x_Aa4',
    spoken_languages: ['English'],
    production_companies: [
      { id: 174, name: 'Warner Bros. Pictures' },
      { id: 101405, name: '6th & Idaho' },
      { id: 128064, name: 'DC Films' },
    ],
  },
  {
    id: 129,
    title: 'Spirited Away',
    tagline: 'Tunnel into a miraculous world.',
    overview: 'A young girl, Chihiro, becomes trapped in a strange and mysterious spirit world after her parents are transformed into pigs. To survive and find a way to return to the human realm, she takes a job at a magical bathhouse for supernatural spirits.',
    poster_path: 'https://image.tmdb.org/t/p/w780/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/Ab8mkHmkYADjU7wQiOkia99GQI.jpg',
    release_date: '2001-07-20',
    vote_average: 8.5,
    vote_count: 16800,
    popularity: 79.8,
    runtime: 125,
    genres: [
      { id: 16, name: 'Animation' },
      { id: 14, name: 'Fantasy' },
      { id: 12, name: 'Adventure' },
      { id: 10751, name: 'Family' },
    ],
    genre_ids: [16, 14, 12],
    director: 'Hayao Miyazaki',
    cast: [
      { id: 19588, name: 'Rumi Hiiragi', character: 'Chihiro Ogino / Sen (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/dm6VwW04l2LqK0j2b6lq4G3h3r7.jpg' },
      { id: 19589, name: 'Miyu Irino', character: 'Haku (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/hG01U0Kz7B0p7w7M0U8k12k8s2F.jpg' },
      { id: 19590, name: 'Mari Natsuki', character: 'Yubaba / Zeniba (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/5qHNjhtjMD4YWH3ez6CCm2tiq0s.jpg' },
    ],
    budget: 19000000,
    revenue: 395800000,
    status: 'Released',
    trailer_key: 'ByXuk9QqQkk',
    spoken_languages: ['Japanese'],
    production_companies: [
      { id: 10342, name: 'Studio Ghibli' },
      { id: 6755, name: 'Tokuma Shoten' },
    ],
  },
  {
    id: 346698,
    title: 'Barbie',
    tagline: 'She\'s everything. He\'s just Ken.',
    overview: 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
    poster_path: 'https://image.tmdb.org/t/p/w780/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/ctMserH8g2SeOAnCw5gFjdQF8io.jpg',
    release_date: '2023-07-21',
    vote_average: 7.1,
    vote_count: 8500,
    popularity: 84.1,
    runtime: 114,
    genres: [
      { id: 35, name: 'Comedy' },
      { id: 12, name: 'Adventure' },
      { id: 14, name: 'Fantasy' },
    ],
    genre_ids: [35, 12, 14],
    director: 'Greta Gerwig',
    cast: [
      { id: 234352, name: 'Margot Robbie', character: 'Barbie', profile_path: 'https://image.tmdb.org/t/p/w300/4g0H4Yn8u9H5J6a7b3c2d1e0f.jpg' },
      { id: 30614, name: 'Ryan Gosling', character: 'Ken', profile_path: 'https://image.tmdb.org/t/p/w300/2A8d0xG7m3X8a1l4j7b0z2x8c.jpg' },
      { id: 1001657, name: 'America Ferrera', character: 'Gloria', profile_path: 'https://image.tmdb.org/t/p/w300/cYg0kLp6m8P2b4n0s8a1m5k8g.jpg' },
      { id: 1158, name: 'Will Ferrell', character: 'Mattel CEO', profile_path: 'https://image.tmdb.org/t/p/w300/4h8r9k0b4v6c7z8a9m0p1q2r3.jpg' },
    ],
    budget: 145000000,
    revenue: 1445638421,
    status: 'Released',
    trailer_key: 'pBk4NYhWNMM',
    spoken_languages: ['English', 'Spanish'],
    production_companies: [
      { id: 174, name: 'Warner Bros. Pictures' },
      { id: 829, name: 'LuckyChap Entertainment' },
      { id: 284, name: 'Mattel Films' },
    ],
  },
  {
    id: 278,
    title: 'The Shawshank Redemption',
    tagline: 'Fear can hold you prisoner. Hope can set you free.',
    overview: 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden.',
    poster_path: 'https://image.tmdb.org/t/p/w780/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    release_date: '1994-09-23',
    vote_average: 8.7,
    vote_count: 27000,
    popularity: 94.0,
    runtime: 142,
    genres: [
      { id: 18, name: 'Drama' },
      { id: 80, name: 'Crime' },
    ],
    genre_ids: [18, 80],
    director: 'Frank Darabont',
    cast: [
      { id: 504, name: 'Tim Robbins', character: 'Andy Dufresne', profile_path: 'https://image.tmdb.org/t/p/w300/dm6VwW04l2LqK0j2b6lq4G3h3r7.jpg' },
      { id: 192, name: 'Morgan Freeman', character: 'Ellis Boyd \'Red\' Redding', profile_path: 'https://image.tmdb.org/t/p/w300/hG01U0Kz7B0p7w7M0U8k12k8s2F.jpg' },
      { id: 4029, name: 'Bob Gunton', character: 'Warden Samuel Norton', profile_path: 'https://image.tmdb.org/t/p/w300/5qHNjhtjMD4YWH3ez6CCm2tiq0s.jpg' },
    ],
    budget: 25000000,
    revenue: 28341469,
    status: 'Released',
    trailer_key: 'PLl99DlL6b4',
    spoken_languages: ['English'],
    production_companies: [
      { id: 97, name: 'Castle Rock Entertainment' },
      { id: 174, name: 'Warner Bros. Pictures' },
    ],
  },
  {
    id: 238,
    title: 'The Godfather',
    tagline: 'An offer you can\'t refuse.',
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
    poster_path: 'https://image.tmdb.org/t/p/w780/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/tmU7GeKVybMWF92Q2tczenGFgUt.jpg',
    release_date: '1972-03-14',
    vote_average: 8.7,
    vote_count: 20400,
    popularity: 91.5,
    runtime: 175,
    genres: [
      { id: 18, name: 'Drama' },
      { id: 80, name: 'Crime' },
    ],
    genre_ids: [18, 80],
    director: 'Francis Ford Coppola',
    cast: [
      { id: 3084, name: 'Marlon Brando', character: 'Don Vito Corleone', profile_path: 'https://image.tmdb.org/t/p/w300/dm6VwW04l2LqK0j2b6lq4G3h3r7.jpg' },
      { id: 1158, name: 'Al Pacino', character: 'Michael Corleone', profile_path: 'https://image.tmdb.org/t/p/w300/hG01U0Kz7B0p7w7M0U8k12k8s2F.jpg' },
      { id: 3085, name: 'James Caan', character: 'Sonny Corleone', profile_path: 'https://image.tmdb.org/t/p/w300/5qHNjhtjMD4YWH3ez6CCm2tiq0s.jpg' },
      { id: 3087, name: 'Robert Duvall', character: 'Tom Hagen', profile_path: 'https://image.tmdb.org/t/p/w300/1s2d3f4g5h6j7k8l9z0x1c2v3.jpg' },
    ],
    budget: 6000000,
    revenue: 245066411,
    status: 'Released',
    trailer_key: 'sY1S34973zA',
    spoken_languages: ['English', 'Italian', 'Latin'],
    production_companies: [
      { id: 4, name: 'Paramount' },
      { id: 10211, name: 'Alfran Productions' },
    ],
  },
  {
    id: 19995,
    title: 'Avatar',
    tagline: 'Enter the world of Pandora.',
    overview: 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization that has become his home.',
    poster_path: 'https://image.tmdb.org/t/p/w780/kyeqWdyUXW608qlYkRqosgbbJyK.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/vL5LR6WdxWPjCmvzy42EdvIe7U6.jpg',
    release_date: '2009-12-18',
    vote_average: 7.6,
    vote_count: 31000,
    popularity: 87.4,
    runtime: 162,
    genres: [
      { id: 28, name: 'Action' },
      { id: 12, name: 'Adventure' },
      { id: 14, name: 'Fantasy' },
      { id: 878, name: 'Science Fiction' },
    ],
    genre_ids: [28, 12, 14, 878],
    director: 'James Cameron',
    cast: [
      { id: 65731, name: 'Sam Worthington', character: 'Jake Sully', profile_path: 'https://image.tmdb.org/t/p/w300/4g0H4Yn8u9H5J6a7b3c2d1e0f.jpg' },
      { id: 8691, name: 'Zoe Saldaña', character: 'Neytiri', profile_path: 'https://image.tmdb.org/t/p/w300/2A8d0xG7m3X8a1l4j7b0z2x8c.jpg' },
      { id: 10205, name: 'Sigourney Weaver', character: 'Dr. Grace Augustine', profile_path: 'https://image.tmdb.org/t/p/w300/cYg0kLp6m8P2b4n0s8a1m5k8g.jpg' },
    ],
    budget: 237000000,
    revenue: 2923706026,
    status: 'Released',
    trailer_key: '5PSNL1qE6VY',
    spoken_languages: ['English', 'Spanish'],
    production_companies: [
      { id: 25, name: '20th Century Fox' },
      { id: 444, name: 'Lightstorm Entertainment' },
    ],
  },
  {
    id: 507089,
    title: 'Five Nights at Freddy\'s',
    tagline: 'Can you survive five nights?',
    overview: 'Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear\'s Pizzeria. But he soon discovers that nothing at Freddy\'s is what it seems.',
    poster_path: 'https://image.tmdb.org/t/p/w780/j9XKiZrVeViAixVRzCta7ge1jw7.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/t5zCBSB5xMDKcDqe91qR8UC3TC3.jpg',
    release_date: '2023-10-27',
    vote_average: 7.5,
    vote_count: 4200,
    popularity: 72.8,
    runtime: 110,
    genres: [
      { id: 27, name: 'Horror' },
      { id: 9648, name: 'Mystery' },
    ],
    genre_ids: [27, 9648],
    director: 'Emma Tammi',
    cast: [
      { id: 27972, name: 'Josh Hutcherson', character: 'Mike Schmidt', profile_path: 'https://image.tmdb.org/t/p/w300/4g0H4Yn8u9H5J6a7b3c2d1e0f.jpg' },
      { id: 10427, name: 'Matthew Lillard', character: 'Steve Raglan / William Afton', profile_path: 'https://image.tmdb.org/t/p/w300/2A8d0xG7m3X8a1l4j7b0z2x8c.jpg' },
      { id: 15303, name: 'Elizabeth Lail', character: 'Vanessa Shelly', profile_path: 'https://image.tmdb.org/t/p/w300/cYg0kLp6m8P2b4n0s8a1m5k8g.jpg' },
    ],
    budget: 20000000,
    revenue: 297144138,
    status: 'Released',
    trailer_key: '0VH9WCFV6XQ',
    spoken_languages: ['English'],
    production_companies: [
      { id: 3172, name: 'Blumhouse Productions' },
      { id: 33, name: 'Universal Pictures' },
    ],
  },
  {
    id: 1184918,
    title: 'The Wild Robot',
    tagline: 'Discover your true nature.',
    overview: 'After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island\'s animals and cares for an orphaned baby goose.',
    poster_path: 'https://image.tmdb.org/t/p/w780/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/417tYZ4ARUyKLgPcBhqiqPqikNZ.jpg',
    release_date: '2024-09-27',
    vote_average: 8.4,
    vote_count: 3800,
    popularity: 93.6,
    runtime: 102,
    genres: [
      { id: 16, name: 'Animation' },
      { id: 878, name: 'Science Fiction' },
      { id: 10751, name: 'Family' },
      { id: 18, name: 'Drama' },
    ],
    genre_ids: [16, 878, 10751, 18],
    director: 'Chris Sanders',
    cast: [
      { id: 1267329, name: 'Lupita Nyong\'o', character: 'Roz (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/4g0H4Yn8u9H5J6a7b3c2d1e0f.jpg' },
      { id: 1083010, name: 'Pedro Pascal', character: 'Fink (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/2A8d0xG7m3X8a1l4j7b0z2x8c.jpg' },
      { id: 1245709, name: 'Kit Connor', character: 'Brightbill (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/cYg0kLp6m8P2b4n0s8a1m5k8g.jpg' },
      { id: 1370, name: 'Bill Nighy', character: 'Longneck (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/4h8r9k0b4v6c7z8a9m0p1q2r3.jpg' },
    ],
    budget: 78000000,
    revenue: 308000000,
    status: 'Released',
    trailer_key: '67vbA5ZJb3s',
    spoken_languages: ['English'],
    production_companies: [
      { id: 521, name: 'DreamWorks Animation' },
      { id: 33, name: 'Universal Pictures' },
    ],
  },
  {
    id: 1034541,
    title: 'Terrifier 3',
    tagline: 'Christmas will never be the same again.',
    overview: 'Art the Clown is set to unleash chaos on the unsuspecting residents of Miles County as they peacefully drift off to sleep on Christmas Eve.',
    poster_path: 'https://image.tmdb.org/t/p/w780/63UkzOpn1bVj9V29Qc6j6x0w20q.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/18TSJF1WLA4CkymvPGkpQD2f4pm.jpg',
    release_date: '2024-10-11',
    vote_average: 6.9,
    vote_count: 1450,
    popularity: 81.2,
    runtime: 125,
    genres: [
      { id: 27, name: 'Horror' },
      { id: 53, name: 'Thriller' },
    ],
    genre_ids: [27, 53],
    director: 'Damien Leone',
    cast: [
      { id: 15303, name: 'David Howard Thornton', character: 'Art the Clown', profile_path: 'https://image.tmdb.org/t/p/w300/dm6VwW04l2LqK0j2b6lq4G3h3r7.jpg' },
      { id: 1810, name: 'Lauren LaVera', character: 'Sienna Shaw', profile_path: 'https://image.tmdb.org/t/p/w300/hG01U0Kz7B0p7w7M0U8k12k8s2F.jpg' },
    ],
    budget: 2000000,
    revenue: 85000000,
    status: 'Released',
    trailer_key: '87X_897k3-8',
    spoken_languages: ['English'],
    production_companies: [
      { id: 1000, name: 'Cineverse' },
      { id: 1001, name: 'Dark Age Cinema' },
    ],
  },
  {
    id: 933260,
    title: 'The Substance',
    tagline: 'If you respect the balance, what could go wrong?',
    overview: 'A fading celebrity takes a black-market drug: a cell-replicating substance that temporarily creates a younger, better version of herself.',
    poster_path: 'https://image.tmdb.org/t/p/w780/lqoMzCcZYEFK729Fc6r4n3NTsaW.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/7h6TqPB3ES54uv8WEnslduIq80w.jpg',
    release_date: '2024-09-20',
    vote_average: 7.3,
    vote_count: 2400,
    popularity: 85.7,
    runtime: 141,
    genres: [
      { id: 27, name: 'Horror' },
      { id: 878, name: 'Science Fiction' },
      { id: 18, name: 'Drama' },
    ],
    genre_ids: [27, 878, 18],
    director: 'Coralie Fargeat',
    cast: [
      { id: 12519, name: 'Demi Moore', character: 'Elisabeth Sparkle', profile_path: 'https://image.tmdb.org/t/p/w300/4g0H4Yn8u9H5J6a7b3c2d1e0f.jpg' },
      { id: 1373737, name: 'Margaret Qualley', character: 'Sue', profile_path: 'https://image.tmdb.org/t/p/w300/2A8d0xG7m3X8a1l4j7b0z2x8c.jpg' },
      { id: 103, name: 'Dennis Quaid', character: 'Harvey', profile_path: 'https://image.tmdb.org/t/p/w300/cYg0kLp6m8P2b4n0s8a1m5k8g.jpg' },
    ],
    budget: 17500000,
    revenue: 55000000,
    status: 'Released',
    trailer_key: 'LNlrGhPp51A',
    spoken_languages: ['English', 'French'],
    production_companies: [
      { id: 2548, name: 'Working Title Films' },
      { id: 1024, name: 'MUBI' },
    ],
  },
  {
    id: 1022789,
    title: 'Inside Out 2',
    tagline: 'Make room for new emotions.',
    overview: 'Teenager Riley\'s mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust aren\'t sure how to feel when Anxiety shows up, and she isn\'t alone.',
    poster_path: 'https://image.tmdb.org/t/p/w780/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/xg27NrXi7EgDXUrbtVfsa9mAngr.jpg',
    release_date: '2024-06-14',
    vote_average: 7.6,
    vote_count: 5100,
    popularity: 91.0,
    runtime: 96,
    genres: [
      { id: 16, name: 'Animation' },
      { id: 10751, name: 'Family' },
      { id: 35, name: 'Comedy' },
      { id: 12, name: 'Adventure' },
    ],
    genre_ids: [16, 10751, 35, 12],
    director: 'Kelsey Mann',
    cast: [
      { id: 16828, name: 'Amy Poehler', character: 'Joy (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/4g0H4Yn8u9H5J6a7b3c2d1e0f.jpg' },
      { id: 1391986, name: 'Maya Hawke', character: 'Anxiety (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/2A8d0xG7m3X8a1l4j7b0z2x8c.jpg' },
      { id: 1373737, name: 'Kensington Tallman', character: 'Riley Andersen (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/cYg0kLp6m8P2b4n0s8a1m5k8g.jpg' },
    ],
    budget: 200000000,
    revenue: 1697200000,
    status: 'Released',
    trailer_key: 'LEjhY15eCx0',
    spoken_languages: ['English'],
    production_companies: [
      { id: 3, name: 'Pixar' },
      { id: 2, name: 'Walt Disney Pictures' },
    ],
  },
  {
    id: 533535,
    title: 'Deadpool & Wolverine',
    tagline: 'Come together.',
    overview: 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
    poster_path: 'https://image.tmdb.org/t/p/w780/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1jv8uaC.jpg',
    release_date: '2024-07-26',
    vote_average: 7.7,
    vote_count: 5900,
    popularity: 97.5,
    runtime: 128,
    genres: [
      { id: 28, name: 'Action' },
      { id: 35, name: 'Comedy' },
      { id: 878, name: 'Science Fiction' },
    ],
    genre_ids: [28, 35, 878],
    director: 'Shawn Levy',
    cast: [
      { id: 10859, name: 'Ryan Reynolds', character: 'Wade Wilson / Deadpool', profile_path: 'https://image.tmdb.org/t/p/w300/4g0H4Yn8u9H5J6a7b3c2d1e0f.jpg' },
      { id: 6968, name: 'Hugh Jackman', character: 'Logan / Wolverine', profile_path: 'https://image.tmdb.org/t/p/w300/2A8d0xG7m3X8a1l4j7b0z2x8c.jpg' },
      { id: 2058, name: 'Emma Corrin', character: 'Cassandra Nova', profile_path: 'https://image.tmdb.org/t/p/w300/cYg0kLp6m8P2b4n0s8a1m5k8g.jpg' },
      { id: 500, name: 'Matthew Macfadyen', character: 'Mr. Paradox', profile_path: 'https://image.tmdb.org/t/p/w300/4h8r9k0b4v6c7z8a9m0p1q2r3.jpg' },
    ],
    budget: 200000000,
    revenue: 1338000000,
    status: 'Released',
    trailer_key: '73_1biulkYk',
    spoken_languages: ['English', 'French'],
    production_companies: [
      { id: 420, name: 'Marvel Studios' },
      { id: 104228, name: 'Maximum Effort' },
      { id: 2575, name: '21 Laps Entertainment' },
    ],
  },
  {
    id: 1111873,
    title: 'Gladiator II',
    tagline: 'What we do in life echoes in eternity.',
    overview: 'Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius must enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist.',
    poster_path: 'https://image.tmdb.org/t/p/w780/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/euYIwmwkmz95mnXvufEmbL6ovhA.jpg',
    release_date: '2024-11-22',
    vote_average: 6.8,
    vote_count: 2200,
    popularity: 90.5,
    runtime: 148,
    genres: [
      { id: 28, name: 'Action' },
      { id: 12, name: 'Adventure' },
      { id: 18, name: 'Drama' },
    ],
    genre_ids: [28, 12, 18],
    director: 'Ridley Scott',
    cast: [
      { id: 2245139, name: 'Paul Mescal', character: 'Lucius Verus', profile_path: 'https://image.tmdb.org/t/p/w300/4g0H4Yn8u9H5J6a7b3c2d1e0f.jpg' },
      { id: 5292, name: 'Denzel Washington', character: 'Macrinus', profile_path: 'https://image.tmdb.org/t/p/w300/2A8d0xG7m3X8a1l4j7b0z2x8c.jpg' },
      { id: 1083010, name: 'Pedro Pascal', character: 'General Acacius', profile_path: 'https://image.tmdb.org/t/p/w300/cYg0kLp6m8P2b4n0s8a1m5k8g.jpg' },
      { id: 934, name: 'Connie Nielsen', character: 'Lucilla', profile_path: 'https://image.tmdb.org/t/p/w300/4h8r9k0b4v6c7z8a9m0p1q2r3.jpg' },
    ],
    budget: 210000000,
    revenue: 460000000,
    status: 'Released',
    trailer_key: '4rgYUipGJNo',
    spoken_languages: ['English', 'Latin'],
    production_companies: [
      { id: 4, name: 'Paramount' },
      { id: 1645, name: 'Scott Free Productions' },
    ],
  },
  {
    id: 912649,
    title: 'Venom: The Last Dance',
    tagline: '\'Til death do them part.',
    overview: 'Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie\'s last dance.',
    poster_path: 'https://image.tmdb.org/t/p/w780/aosm8NMQ3UzyAcg7vm87wh5Q02q.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/3V4kStowL7IlfZ8VO61WIr1W79R.jpg',
    release_date: '2024-10-25',
    vote_average: 6.8,
    vote_count: 2600,
    popularity: 88.0,
    runtime: 109,
    genres: [
      { id: 28, name: 'Action' },
      { id: 878, name: 'Science Fiction' },
      { id: 12, name: 'Adventure' },
    ],
    genre_ids: [28, 878, 12],
    director: 'Kelly Marcel',
    cast: [
      { id: 2524, name: 'Tom Hardy', character: 'Eddie Brock / Venom', profile_path: 'https://image.tmdb.org/t/p/w300/d8joFvjghvPhXo14pAasfD7fA.jpg' },
      { id: 1267329, name: 'Chiwetel Ejiofor', character: 'Rex Strickland', profile_path: 'https://image.tmdb.org/t/p/w300/4g0H4Yn8u9H5J6a7b3c2d1e0f.jpg' },
      { id: 5081, name: 'Juno Temple', character: 'Dr. Teddy Payne', profile_path: 'https://image.tmdb.org/t/p/w300/hG01U0Kz7B0p7w7M0U8k12k8s2F.jpg' },
    ],
    budget: 120000000,
    revenue: 477000000,
    status: 'Released',
    trailer_key: '__2bjWbetsA',
    spoken_languages: ['English'],
    production_companies: [
      { id: 5, name: 'Columbia Pictures' },
      { id: 7505, name: 'Marvel Entertainment' },
    ],
  },
  {
    id: 1064010,
    title: 'Moana 2',
    tagline: 'The ocean is calling her back.',
    overview: 'After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a brand-new crew of unlikely seafarers to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she\'s ever faced.',
    poster_path: 'https://image.tmdb.org/t/p/w780/yh64qw9mgXBvlaWDi7Q9tpUBAvH.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/tElnmtQ6yz1PjN1kePNt8cuBHnO.jpg',
    release_date: '2024-11-27',
    vote_average: 7.0,
    vote_count: 1800,
    popularity: 89.4,
    runtime: 100,
    genres: [
      { id: 16, name: 'Animation' },
      { id: 12, name: 'Adventure' },
      { id: 10751, name: 'Family' },
      { id: 35, name: 'Comedy' },
      { id: 10402, name: 'Music' },
    ],
    genre_ids: [16, 12, 10751, 35],
    director: 'David G. Derrick Jr., Jason Hand, Dana Ledoux Miller',
    cast: [
      { id: 1564846, name: 'Auli\'i Cravalho', character: 'Moana (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/4g0H4Yn8u9H5J6a7b3c2d1e0f.jpg' },
      { id: 18918, name: 'Dwayne Johnson', character: 'Maui (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/2A8d0xG7m3X8a1l4j7b0z2x8c.jpg' },
      { id: 1245, name: 'Alan Tudyk', character: 'Heihei (voice)', profile_path: 'https://image.tmdb.org/t/p/w300/cYg0kLp6m8P2b4n0s8a1m5k8g.jpg' },
    ],
    budget: 150000000,
    revenue: 1050000000,
    status: 'Released',
    trailer_key: 'hDZ7y8RP5HE',
    spoken_languages: ['English'],
    production_companies: [
      { id: 2, name: 'Walt Disney Pictures' },
      { id: 6125, name: 'Walt Disney Animation Studios' },
    ],
  },
  {
    id: 1100782,
    title: 'Smile 2',
    tagline: 'It\'s the last thing you\'ll see.',
    overview: 'About to embark on a new world tour, global pop sensation Skye Riley begins experiencing increasingly terrifying and inexplicable events. Overwhelmed by the escalating horrors and the pressures of fame, Skye is forced to face her dark past.',
    poster_path: 'https://image.tmdb.org/t/p/w780/aE85MnPIvQO79pOH5ynkO9qB2fE.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/original/iR79ciqhtgeh9uv70Gv4xioDY09.jpg',
    release_date: '2024-10-18',
    vote_average: 6.8,
    vote_count: 1300,
    popularity: 77.4,
    runtime: 127,
    genres: [
      { id: 27, name: 'Horror' },
      { id: 9648, name: 'Mystery' },
    ],
    genre_ids: [27, 9648],
    director: 'Parker Finn',
    cast: [
      { id: 1245709, name: 'Naomi Scott', character: 'Skye Riley', profile_path: 'https://image.tmdb.org/t/p/w300/4g0H4Yn8u9H5J6a7b3c2d1e0f.jpg' },
      { id: 10427, name: 'Rosemarie DeWitt', character: 'Elizabeth Riley', profile_path: 'https://image.tmdb.org/t/p/w300/2A8d0xG7m3X8a1l4j7b0z2x8c.jpg' },
      { id: 15303, name: 'Lukas Gage', character: 'Lewis Fregoli', profile_path: 'https://image.tmdb.org/t/p/w300/cYg0kLp6m8P2b4n0s8a1m5k8g.jpg' },
    ],
    budget: 28000000,
    revenue: 137000000,
    status: 'Released',
    trailer_key: '0HY6QFlBzho',
    spoken_languages: ['English'],
    production_companies: [
      { id: 4, name: 'Paramount' },
      { id: 1645, name: 'Temple Hill Entertainment' },
    ],
  },
];
